version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pos_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pos_db
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Garante que os dados não se percam

volumes:
  db_data: